[workspace]
members = ["core", "tests"]
resolver = "2"

[workspace.dependencies]
pest = "2.8.0"
pest_derive = "2.8.0"
thiserror = "2"
core = { path = "./core" }
builder = { git = "https://github.com/NeroWeNeed/builder" } 
getter = { git = "https://github.com/NeroWeNeed/getter" } 
